<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_BLOCK_TITLE' => 'ANFORDERUNGSLISTE FÜR DIE STORNIERUNG VON BESTELLUNGEN',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ORDERID' => 'CHECK24 ID',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ORDERNR' => 'OXID Bestellnr',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ACTION' => 'Aktion',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_TIME' => 'Zeit',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_DENY_REASON' => 'Begründung der Verweigerung',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_CONFIRM' => 'Änderung bestätigen',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_DENY' => 'Änderung verweigern',
    'CHECK24CONNECTOR_ORDERCHANGE_IMPORT_TITLE' => 'Auftrags- und Auftragsänderungsimport',
    'CHECK24_REQUEST_LIST_TIME' => 'Zeit',
    'CHECK24_REQUEST_LIST_ORDERID' => 'CHECK24 ID',
    'CHECK24_REQUEST_LIST_ACTION' => 'Aktion',
    'CHECK24_REQUEST_LIST_RESPONSE' => 'Antwort',
    'CHECK24_REQUEST_LIST_REASON' => 'Begründung der Verweigerung',
    'check24connector_requestlist' => 'CHECK24 Anforderungsliste',
    'CHECK24_RESPONSE_CONFIRM_TITLE' => 'bestätigt',
    'CHECK24_RESPONSE_REJECT_TITLE' => 'abgelehnt',
    'CHECK24_ACTION_REQUEST_TITLE' => 'returnrequest',
    'CHECK24_ACTION_CONFIRMATION_TITLE' => 'cancellationrequest',
    'CHECK24_NO_RESPONSE_TITLE' => 'ausstehend',
    'ITRCHECK24_TOOLTIPS_ITEM_CONFIRM_REQUEST' => 'Änderung bestätigen',
    'ITRCHECK24_TOOLTIPS_ITEM_REJECT_REQUEST' => 'Änderung verweigern',
    'CHECK24CONNECTOR_REQUEST_LIST_YOUWANTTOCONFIRM' => 'Möchten Sie die Anfrage bestätigen?',
    'CHECK24CONNECTOR_REQUEST_LIST_YOUWANTTOREJECT' => 'Möchten Sie die Anfrage ablehnen?',
    'ITRCHECK24CONNECTOR_REJECT_REASON_PLACEHOLDER' => 'Bitte geben Sie den Grund für die Ablehnung des Auftrags ein.',
    'ITRCHECK24CONNECTOR_REJECT_SUBMIT' => 'Speichern',
    'ITRCHECK24CONNECTOR_REJECT_CANCEL' => 'Abbrechen',
    'ITRCHECK24CONNECTOR_SETTINGS_HEADER_TEXT' => 'Einstellungen',
    'ITRCHECK24CONNECTOR_SETTINGS_MODULE_ACTIVE' => 'Modul aktiv',
    'ITRCHECK24CONNECTOR_SETTINGS_MODULE_ACTIVE_INFO' => 'Durch das aktivieren des Moduls werden noch keine Importe ausgel&ouml;st. Lösen sie die Importe gem&auml;&szlig; Anleitung aus, z.B. zeitgesteuert.',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_USER' => 'FTP User',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_USER_INFO' => 'Bsp.: partner12345',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PASSWORD' => 'FTP Pass',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PASSWORD_INFO' => 'Bsp.: ab12xy',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_HOST' => 'FTP Host',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_HOST_INFO' => 'Bsp.: partnerftp.testsieger.de',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PORT' => 'FTP Port',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PORT_INFO' => 'Bsp.: 44021',
    'ITRCHECK24CONNECTOR_SETTINGS_DELIVERY_METHOD' => 'Versandart',
    'ITRCHECK24CONNECTOR_SETTINGS_DELIVERY_METHOD_INFO' => '&Uuml;berschreibt die importierte Versandart. Leer lassen, um Versandart aus der Importdatei zu &uuml;bernehmen. Bsp.: oxidstandard',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_STANDARD' => 'Standard Zahlungsart',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_STANDARD_INFO' => 'Die Zahlungsart, welche benutzt wird wenn die Zahlungsart von CHECK24 keiner Zahlungsart von Oxid zugewiesen werden kann.',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_CHECK24' => 'CHECK24 Zahlungsart',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_CHECK24_INFO' => 'Wird die Zahlung über CHECK24.de abgewickelt, soll sie mit dieser Bezahlart im Oxid-System erscheinen.
Sofern Sie keine Zahlungen über CHECK24.de abwickeln lassen, wählen Sie eine beliebige Zahlungsart.',
    'ITRCHECK24CONNECTOR_SETTINGS_PLEASE_SELECT' => 'Bitte ausw&auml;hlen!',
    'ITRCHECK24CONNECTOR_SETTINGS_ORDER_CONFIRMATION_BY_EMAIL' => 'Bestellbest&auml;tigung<br>per E-Mail',
    'ITRCHECK24CONNECTOR_SETTINGS_ORDER_CONFIRMATION_BY_EMAIL_INFO' => 'Achtung! Durch das Aktivieren erhält der Kunde eine automatische Bestellbest&auml;tigung bei Bestelleingang. Diese ist NICHT IDENTISCH mit der Oxid-eigenen Bestellbest&auml;tigungsmail, sondern kann in der Datei testsieger_resend_confirm.tpl angepasst werden. Vor der Verwendung pr&uuml;fen!',
    'ITRCHECK24CONNECTOR_SETTINGS_REDUCE_INVENTORY' => 'Lagerbestand<br>reduzieren',
    'ITRCHECK24CONNECTOR_SETTINGS_REDUCE_INVENTORY_INFO' => 'Wenn aktiviert, wird der Lagerbestand der bestellten Artikel um die bestellte Menge reduziert. Die Bestellung wird auch dann importiert, wenn dies zu negativem Lagerbestand führt.',
    'ITRCHECK24CONNECTOR_SETTINGS_LOGDATA' => 'Log-Datei',
    'ITRCHECK24CONNECTOR_SETTINGS_LOGDATA_DELETE' => 'Logdatei l&ouml;schen',
    'ITRCHECK24CONNECTOR_SETTINGS_ORDER_CONFIRMATION_ALERT' => 'Durch das aktivieren erhält der Kunde eine automatische Bestellbestaetigung. \nDiese ist NICHT IDENTISCH mit der Oxid-eigenen Bestellbestaetigungsmail, sondern kann in der Datei testsieger_resend_confirm.tpl angepasst werden. \nVor der Verwendung pruefen!',
    'ITRCHECK24CONNECTOR_IMPORT_ORDERS_NOW' => 'Bestellungen jetzt importieren',
    'ITRCHECK24CONNECTOR_ORDERIMPORT' => 'Bestell-Import',
    'ITRCHECK24CONNECTOR_IMPORT_ORDERCHANGE_NOW' => 'Änderungen jetzt importieren',
    'ITRCHECK24CONNECTOR_ORDERCHANGEIMPORT' => 'Orderchange-Import'
];
