<?php

$sLangName = 'English';

$aLang = [
    'charset' => 'UTF-8',

    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_BLOCK_TITLE' => 'ORDER CANCELLATION REQUEST LIST',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ORDERID' => 'CHECK24 ID',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ORDERNR' => 'OXID OrderNr',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ACTION' => 'Action',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_TIME' => 'Time',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_DENY_REASON' => 'Deny reason',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_CONFIRM' => 'Confirm',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_DENY' => 'Deny',
    'CHECK24CONNECTOR_ORDERCHANGE_IMPORT_TITLE' => 'Order and orderchange import',
    'CHECK24_REQUEST_LIST_TIME' => 'Time',
    'CHECK24_REQUEST_LIST_ORDERID' => 'CHECK24 ID',
    'CHECK24_REQUEST_LIST_ACTION' => 'Action',
    'CHECK24_REQUEST_LIST_RESPONSE' => 'Response',
    'CHECK24_REQUEST_LIST_REASON' => 'Reject reason',
    'check24connector_requestlist' => 'CHECK24 request list',
    'CHECK24_RESPONSE_CONFIRM_TITLE' => 'confirmed',
    'CHECK24_RESPONSE_REJECT_TITLE' => 'rejected',
    'CHECK24_ACTION_REQUEST_TITLE' => 'returnrequest',
    'CHECK24_ACTION_CONFIRMATION_TITLE' => 'cancellationrequest',
    'CHECK24_NO_RESPONSE_TITLE' => 'pending',
    'ITRCHECK24_TOOLTIPS_ITEM_CONFIRM_REQUEST' => 'Confirm request',
    'ITRCHECK24_TOOLTIPS_ITEM_REJECT_REQUEST' => 'Reject request',
    'CHECK24CONNECTOR_REQUEST_LIST_YOUWANTTOCONFIRM' => 'Do you want to confrim the request?',
    'CHECK24CONNECTOR_REQUEST_LIST_YOUWANTTOREJECT' => 'Do you want to reject the request?',
    'ITRCHECK24CONNECTOR_REJECT_REASON_PLACEHOLDER' => 'Please enter request reject reason..',
    'ITRCHECK24CONNECTOR_REJECT_SUBMIT' => 'Save',
    'ITRCHECK24CONNECTOR_REJECT_CANCEL' => 'Cancel',
    'ITRCHECK24CONNECTOR_SETTINGS_HEADER_TEXT' => 'Settings',
    'ITRCHECK24CONNECTOR_SETTINGS_MODULE_ACTIVE' => 'Module aktive',
    'ITRCHECK24CONNECTOR_SETTINGS_MODULE_ACTIVE_INFO' => 'Durch das aktivieren des Moduls werden noch keine Importe ausgel&ouml;st. Lösen sie die Importe gem&auml;&szlig; Anleitung aus, z.B. zeitgesteuert.',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_USER' => 'FTP User',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_USER_INFO' => 'Bsp.: partner12345',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PASSWORD' => 'FTP Pass',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PASSWORD_INFO' => 'Bsp.: ab12xy',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_HOST' => 'FTP Host',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_HOST_INFO' => 'Bsp.: partnerftp.testsieger.de',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PORT' => 'FTP Port',
    'ITRCHECK24CONNECTOR_SETTINGS_FTP_PORT_INFO' => 'Bsp.: 44021',
    'ITRCHECK24CONNECTOR_SETTINGS_DELIVERY_METHOD' => 'Delivery method',
    'ITRCHECK24CONNECTOR_SETTINGS_DELIVERY_METHOD_INFO' => '&Uuml;berschreibt die importierte Versandart. Leer lassen, um Versandart aus der Importdatei zu &uuml;bernehmen. Bsp.: oxidstandard',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_STANDARD' => 'Standard payment method',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_STANDARD_INFO' => 'Die Zahlungsart, welche benutzt wird wenn die Zahlungsart von CHECK24 keiner Zahlungsart von Oxid zugewiesen werden kann.',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_CHECK24' => 'CHECK24 payment method',
    'ITRCHECK24CONNECTOR_SETTINGS_PAYMENT_METHOD_CHECK24_INFO' => 'Wird die Zahlung über CHECK24.de abgewickelt, soll sie mit dieser Bezahlart im Oxid-System erscheinen.
Sofern Sie keine Zahlungen über CHECK24.de abwickeln lassen, wählen Sie eine beliebige Zahlungsart.',
    'ITRCHECK24CONNECTOR_SETTINGS_PLEASE_SELECT' => 'Please select!',
    'ITRCHECK24CONNECTOR_SETTINGS_ORDER_CONFIRMATION_BY_EMAIL' => 'Order confirmation<br>by E-Mail',
    'ITRCHECK24CONNECTOR_SETTINGS_ORDER_CONFIRMATION_BY_EMAIL_INFO' => 'Achtung! Durch das Aktivieren erhält der Kunde eine automatische Bestellbest&auml;tigung bei Bestelleingang. Diese ist NICHT IDENTISCH mit der Oxid-eigenen Bestellbest&auml;tigungsmail, sondern kann in der Datei testsieger_resend_confirm.tpl angepasst werden. Vor der Verwendung pr&uuml;fen!',
    'ITRCHECK24CONNECTOR_SETTINGS_REDUCE_INVENTORY' => 'Reduce<br>stock',
    'ITRCHECK24CONNECTOR_SETTINGS_REDUCE_INVENTORY_INFO' => 'Wenn aktiviert, wird der Lagerbestand der bestellten Artikel um die bestellte Menge reduziert. Die Bestellung wird auch dann importiert, wenn dies zu negativem Lagerbestand führt.',
    'ITRCHECK24CONNECTOR_SETTINGS_LOGDATA' => 'Log data',
    'ITRCHECK24CONNECTOR_SETTINGS_LOGDATA_DELETE' => 'Delete log data',
    'ITRCHECK24CONNECTOR_SETTINGS_ORDER_CONFIRMATION_ALERT' => 'Durch das aktivieren erhält der Kunde eine automatische Bestellbestaetigung. \nDiese ist NICHT IDENTISCH mit der Oxid-eigenen Bestellbestaetigungsmail, sondern kann in der Datei testsieger_resend_confirm.tpl angepasst werden. \nVor der Verwendung pruefen!',
    'ITRCHECK24CONNECTOR_IMPORT_ORDERS_NOW' => 'Bestellungen jetzt importieren',
    'ITRCHECK24CONNECTOR_ORDERIMPORT' => 'Bestell-Import',
    'ITRCHECK24CONNECTOR_IMPORT_ORDERCHANGE_NOW' => 'Änderungen jetzt importieren',
    'ITRCHECK24CONNECTOR_ORDERCHANGEIMPORT' => 'Orderchange-Import'
];
