<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_BLOCK_TITLE' => 'ORDER CANCELLATION REQUEST LIST',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ORDERID' => 'CHECK24 ID',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ORDERNR' => 'OXID OrderNr',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_ACTION' => 'Action',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_TIME' => 'Time',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_DENY_REASON' => 'Deny reason',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_CONFIRM' => 'Confirm',
    'TSCHECK24CONNECTOR_ORDERCHANGE_REQUEST_DENY' => 'Deny'
];
